name: Create and Commit Plugin ZIP

on:
  push:
    branches:
      - master
    paths:
      - 'wp-content/plugins/iranian-league-table/**'

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important for push permissions

      - name: Create ZIP archive
        run: |
          cd wp-content/plugins
          zip -r ../../iranian-league-table.zip iranian-league-table

      - name: Commit and push ZIP file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git
          git config --global user.email "arma@jangal.co"
          git config --global user.name "Arma"

          # Add and commit the ZIP file
          git add iranian-league-table.zip
          git commit -m "chore: Update plugin ZIP file [skip ci]"

          # Push changes
          git push origin HEAD:master